### ISSUE TITLE
Suggestions towards making this "the best" tool for Gulp with M2

### ISSUE THREAD

**Issue by alankent** [SnowdogApps/magento2-frontools#1]
Hi, I thought I would create an issue here to capture discussion. The one in the M2 GitHub felt like the wrong place for the discussion.

**Comment by alankent** [comment]
I did not notice the configs/themes.json file. Seems to work.

How does 'watch' work? Does it work out all the imports so get exact file imports worked out correctly?

I found that the watch list I set up by hand for styles-l for example was different from a custom Less file I create locally. Do source maps solve that problem? For example, I was watching **/_*.less (note the leading underscore) so styles-l only rebuilt if a file starting with '_' was changed, as our library files follow this convention. Oh, and the styles-l.less file of course!

The extra Less files added by a theme I was just using **/*.less (if anything changes, just recompile). Seemed pretty easy.  But it also felt silly - we have the `@import` statements. Why doesn't watch *know* what files to monitor automatically?

Next question was how to package the code. Should it be a Composer package so it drops in under 'vendor'? Or a ZIP file you install by hand? I am interested in having a 'nice' installation and upgrade experience, but not sure if Gulpfile.js must be in the root directory of M2 for example - in which case how would you install it normally?

PS: If it works nicely, I am thinking of including in a M2 Docker image for development I am building up if that is okay. LiveReload was a pain there because it required configuration *outside* the Docker container.

**Comment by Igloczek** [comment]
Hm.... I don't get first question or it's too strange :) Will try to just describe how `watch` task work for default themes, hope it helps.

1. Each trough all locales of theme
2. Get `dest` path of theme and add `/**/*.less`, to be able to watch changes on every `less` file in every folder inside `dest`
3. Build name of task to run i.e. `less:luma:en_US`
4. Setup `gulp.watch` using this data
5. On every change defined task compile all `less` files defined in `configs/themes.json` as `files` array, for given locale.

---

Suggest to use it via composer, should be the easies way to maintain in future (i.e. define version), but not sure how to handle customizations, because there are ignored by git... Maybe fork and customize on it?

I don't recommend placing everything manually in root directory, because it will override `package.json` and `grunt` will be no longer operating. For now I build this as extension, not override.

**Comment by alankent** [comment]
If I have A.less that imports B.less but not C.less in the same directory, then A.less only needs converting to A.css if A.less or B.less are modified - it does not need redoing if C.less is touched.

How do you work out these dependencies? Well, there are @import statements inside the files with relative paths - a program *can* work out the precise list of files to watch. Why doesn't gulp do that? That would be much more precise than **/*.less.  If any file changes, the work out the dependency chain again (a new import might have been added).

My hack was for styles-l.css, styles-m.css, print.css, email.css (our standard files) was to make them watch **/_*.less (only files with a leading underscore) and styles-l.less, styles-m.less, print.less, email.less. Only _XXX.less files are imported, by default, and I am proposing developers add new CSS files (not extend our files). This avoids rebuilding styles-l et al each time you touch B.less. Much faster. But it analysing @import statements in the source files would be better still.

**Comment by Igloczek** [comment]
Ok, I got it :)
There is one big problem - imports can exists in imported files and i.e. variable inside file imported by other file might be defined in another file, not imported directly from main file - there is no way to track that chain and that's why we rebuild everything over and over.

Your approach of adding additional main files instead of extending/changing main styles isn't good, this leads to overrides on CSS specificity level and might be tricky, especially without strict styles methodology. Some dev might start to scream "we are doomed".

**Comment by LeonB** [comment]
Awesome work! If there's anything I can do: please let me know!

**Comment by LeonB** [comment]
One thing I would like to see: sassc / libsass support

**Comment by Igloczek** [comment]
@LeonB Thanks! Libsass is supported out of thx box via `gulp-sass` plugin. Set `"lang": "sass"` in `configs/themes.json` for your custom theme and everything should work fine :)

**Comment by alankent** [comment]
Hi @Igloczek - regarding the nested imports problem, that seems pretty easy to solve. You just follow the chain of import statements (with infinite recursion protection if you want to be safe).

Pseudo code:

    findAllImports(filename, array of file names) {
        read filename
        find all @import statements using regex or similar
        foreach @import {
            resolve filename relative to current filename (could be a relative path)
            if resolved filename is not in the array already {
                add the resolved filename to the array to return
                call findAllImports(resolvedFilename) to get any imports from the referenced file
            }
        }
    }

Or am I missing something?

Regarding the point of adding new files, is there good reading on this? I am admittedly not a front end dev so I would like to better understand "the norm" here. I am trying to piece it together from different comments I hear.

For example, we have a `_theme.less` file which allows a theme to override the variables used by the Magento UI Less mixins. So you change that file to make all buttons look different. That does not need a new CSS file added to a page.

But sometimes you introduce new CSS class names in a module because there is some new HTML markup that needs something different. In *this* case I was thinking you would add a new CSS file. Many modules would not need to.

The last step is merging CSS files for performance. Magento has a tool to merge CSS files, but I am wondering if a better approach is to have a Less (?) file in the theme that imports all the other Less/CSS files. The HTML page then includes that single CSS file. That leaves final control with the frontend dev, allowing sourcemaps/minification/whatever using Gulp tools.

**Comment by Igloczek** [comment]
Digging in files always leads to weird solutions, like `@magento-import` :wink: 
To be honest, I'm not convinced to idea of hacking watch task as a right way to handle "obesity" of theme.
Also in Gulp we can't pass parameters to tasks in straight way, so have to use some kind of global object, adding more complexity, just for faster `less` compilation in some cases.

**Comment by alankent** [comment]
I don't think it is worthwhile keeping this open - pretty well everything was addressed - new issues can be created for other topics. (Reopen if you disagree.)
