### ISSUE TITLE
Why drop LESS support before Magento?

### ISSUE THREAD

**Issue by simonsaysforcepush** [SnowdogApps/magento2-frontools#124]
I understand the switch to SASS, and I understand that Magento is supposedly going to drop LESS support eventually, but why would you drop LESS support BEFORE Magento? This makes working on current projects and projects that are based on previous versions of Magento very difficult. Why not include both LESS and SASS? Now I have to fork it myself in order to continue using it? Ridiculous.

**Comment by Igloczek** [comment]
First of all -> we are not Magento, so we are not going to stick with their release plans or other related things.
This tools are mostly build for our internal, Snowdog, needs, but also designed to fit needs of other developers in community. 

If this design doesn't fit you, build own solution, customize this one... do whatever you want, but not blame us that we drop support for something not used in our projects or at most community projects (https://twitter.com/Igloczek/status/775233138784145408).

> Why not include both LESS and SASS?

B/c maintaining both is PITA. We have limited time to work on this tools, so decide to push forward, instead of supporting lang without any future.

If you need LESS support (as mention in docs)
> Feel free to use older version (0.11.4 and lower)
