### ISSUE TITLE
Theme name is added to sourcePath for files in view_preprocessed

### ISSUE THREAD

**Issue by WouterSteen** [SnowdogApps/magento2-frontools#127]
I have a theme, Mijnheer/default with a Magento_Theme/styles/_modules.scss

When I run gulp dev, dirs and symlinks are created like this:
`var/view_preprocessed/frontools/frontend/Mijnheer/default/nl_NL/Default/Magento_Theme/styles/_module.scss`

This will not work because the gulp watchers are watching in this this:
`var/view_preprocessed/frontools/frontend/Mijnheer/default/nl_NL/Default/Magento_Theme`

I fixed this for now to strip the /Default from the source path like this:
`tools/helper/inheritance-resolver.js` 
line 76
`themeDest + '/' + locale + srcPath.replace(themeSrc, '').replace('/Default', '')`

I'm not sure if this is a bug or a setting i'm not seeing.
I will look into this later.

**Comment by Igloczek** [comment]
Could you show me your themes.json file?

**Comment by Igloczek** [comment]
I'm pretty sure that you have `Default` directory somewhere in your theme, which is not correct. Probably you have something like `Mijnheer/default/Default` instead of just `Mijnheer/default` or you defined wrong paths in `themes.json` file.
There is no way that Frontools create this directory from nothing.
