### ISSUE TITLE
npm get error when install frontools

### ISSUE THREAD

**Issue by mrtuvn** [SnowdogApps/magento2-frontools#130]
```
npm ERR! Linux 4.8.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```

**Comment by ennostuurman** [comment]
@mrtuvn => this is an issue with npm fsevents which is an OS X only dependency of browser-sync and will cause the NPM ERR! on non OS X operating systems like Linux.

Change your package json so fsevents will become an optional dependency and run npm install (will throw WARN not ERR!) or npm install --no-optional .

Frontools package.json addition at the end of file:

```
 "stylelint": "~7.5.0"
  },
  "optionalDependencies": {
    "fsevents": "*"
  }
}
```

Or use yarn instead of npm (frontools 1.x) which deals better with the fsevents dependency issue.

**Comment by Igloczek** [comment]
You can also get rid of `npm-shrinkwrap.json` file and generate own (but then it may not work on Mac OS).

But at all, using Yarn seems to be easies (and fastest) way.

**Comment by Igloczek** [comment]
`npm-shrinkwrap.json` file was removed in 1.1.2.
If you want to keep safe versions of dependencies all the time, use Yarn, yarn.lock file is added to repository and will be updated in future.
