### ISSUE TITLE
Create styles.css and print.css in theme directory

### ISSUE THREAD

**Issue by mattkrupnik** [SnowdogApps/magento2-frontools#238]
Hi, 

Is possibility to generate styles in theme directory?
When I use `php bin/magento setup:static-content:deploy` I always must run `gulp styles` to generate it in `pub/static`

**Comment by Igloczek** [comment]
It's not M1 anymore, keeping compiled files in theme or module directory isn't considered as a good practice and I'll not tell you how to do it.

But... you are probably overusing `setup:static-content:deploy` and that's why you try to fix the wrong thing.

Basically, unless your store is in the production mode, you don't have to use this command at all, so it means the only scenario when the styles are gone, is during deployment process and you can easily fix it, adding Frontools compilation tasks after this step in your deployment pipeline.
