### ISSUE TITLE
Maybe Drop Magento Framework dependency 

### ISSUE THREAD

**Issue by amenk** [SnowdogApps/magento2-frontools#277]
The theme does technically not depend on Magento/framework - can we drop the composer dependency ?

Our rationale is as follows:

We compile the theme centrally in a git repo separate from Magento  (the theme is shared with another CMS system). So we had to remove the dependency.

What do you think?

**Comment by Igloczek** [comment]
Frontools don't have any dependencies - https://github.com/SnowdogApps/magento2-frontools/blob/master/composer.json

But talking about themes - we are using same dependencies as Magento is using in their code because it will not let anyone use theme designed for 2.2 on 2.0 etc. and we are not going to change it, b/c this dependency is useful.

**Comment by amenk** [comment]
thanks :)
