### ISSUE TITLE
inheritance of theme partials

### ISSUE THREAD

**Issue by slackerzz** [SnowdogApps/magento2-frontools#36]
Hi, i'm working with your blank theme and frontools 0.9.3.
In my custom theme i've copied `Magento_Checkout/css/source/module/_minicart.scss` from `vendor/snowdog/theme-blank-sass` but if i edit this file i get no result.
So i copied all the css folder from `vendor/snowdog/theme-blank-sass/Magento_Checkout` ans it started to work.

Is this how it should work or i'm missing something?

**Comment by PSDoff** [comment]
@slackerzz What do you mean you get no result? Is there an error in your console when attempting to compile after only copying over `Magento_Checkout/css/source/module/_minicart.scss`? I'm guessing it's saying that the file cannot be found.

This is because inside `Magento_Checkout/css/source/module/_module.scss` is the file that is importing `module/_minicart.scss`. Nested @import directives are not yet supported in Frontools. For the time being, if you need to make customizations to any .scss files in a module, you'll need to copy over the _module.scss file of the module, as well as any files that it explicitly imports.

**Comment by Igloczek** [comment]
It's known "bug" (thanks @PSDoff) - compilation checks only main path i.e. if you copy whole `Magento_Checkout` it would works fine, but single file don't.

For now I recommend to use this script, to create symlinks to parent theme - it's just a workaround.
https://gist.github.com/Igloczek/33f91fedc455321bbbf87480fc557245
Add this script to `tasks` folder and run them before you start styles compilation.

Warning! This will create a lot of symlinks in your child theme directory and probably you shouldn't commit them to repository.

**Comment by slackerzz** [comment]
@PSDoff with "i get no result" i mean that if i make some modification to `Magento_Checkout/css/source/module/_minicart.scss` the complied css dosn't reflect it but there is no error in console.

@Igloczek ty
