### ISSUE TITLE
Breaking changes introduced in minor version

### ISSUE THREAD

**Issue by bassplayer7** [SnowdogApps/magento2-frontools#364]
[v1.8.0 was released recently](https://github.com/SnowdogApps/magento2-frontools/releases/tag/1.8.0) – bringing great changes like Gulp 4. Thanks for your work on this. However, it breaks any Composer dependencies that are set to allow minor `1.x` updates. SemVer requires that all changes are [backward compatible](https://semver.org/#spec-item-7). 

Would it be possible to re-release as version `v2.0.0`? From the outside, this upgrade looks to deserve the new version.

**Comment by Igloczek** [comment]
I decided to keep 1.x just because the breaking changes are minor, do not affect most users and are super easy to update.

Most users will not even fell that something was changed, since the usage of PostCSS plugins configuration requires forking the tools to add new dependencies, while `email-fix` is still available via npm scripts, so in worst case scenario it requires to change `gulp email-fix` to `yarn email-fix`.

**Comment by bassplayer7** [comment]
@Igloczek, I understand. However, since there is the possibility of it affecting some users wouldn't it be better for there to be an opt-in (for those who limit it to not auto-update major version)? Is there a downside to maintaining SemVer here?

It seems possible that the effects are broader then you are thinking, though. In our case, it failed because: there was no `gulpfile.js` found (name changed), the Node version, another unknown error (`Cannot read property 'apply' of undefined`), and I believe something related to `plugins.autoprefixer()` in `themes.json`.

Again, all the changes introduced in the latest release look great, but it would give time to update it if was released per SemVer.

**Comment by Igloczek** [comment]
It's hard to determine what is a breaking change, since a lot of things can be considered as breaking.

If I'll bump the major version, for example, every time the new Node.js is required, since it can be considered as a breaking change, almost every release will be major and will require manual work in all projects.

I'd suggest keeping this dependency added to `composer.json` and locked in `composer.lock` or if you want to stick with for-sure-non-breaking-changes-versions use `~` instead of `^` while specifying a range.

Answering your question - I'm not going to revert this version, since there were already over 150 downloads of it, and it may lead to weird situations, were someone have non-existing 1.8.0 in the lock file.

Out of curiosity - why do you manually look for `gulpfile.js`?

**Comment by StefGeraets** [comment]
Just to leave here as a sort of documentation.
We also had some breaking changes. This was caused by an autoprefixer we use to support css grid on IE.
The old way of autoprefix this was: 
`"postcss": ["plugins.autoprefixer({ grid: true, browsers: ['>1%'] })"]`
In the 1.8 version the prefixer use:
` "postcss": ["autoprefixer({ grid: true})"]`

**Comment by bassplayer7** [comment]
@Igloczek sorry for the delay here. I had opted to lock in the version to patch us through.

> It's hard to determine what is a breaking change, since a lot of things can be considered as breaking.

A breaking change _requires_ external updates. An example of this would be if an update was required to themes.json. I don't think your example of a new Node.js version fits. A new version of Node shouldn't necessarily require an update to a user-provided file because in this case, there are mostly only configuration files. In summary, I think a major version _gauranteed requires_ an external change, while a minor version _may require_ an external update, and a patch should _not require_ an external change.

> Out of curiosity - why do you manually look for `gulpfile.js`?

I use NPM scripts to handle the coordination of the asset pipeline.

**Comment by Igloczek** [comment]
Starting from now the new versions will consider as breaking:
- changes in required Node.js version - because it usually requires changes in deployment pipelines
- major updates of packages that have configuration exposed to the users (for example Autoprefixer, Babel, PostCSS etc.)
- major changes in the files structure (like those introduced during migration to Gulp 4)
- changes in tasks execution - but only renames and removals, adding a new one will be still minor
- changes in configuration files - but only changing the existing, adding a new one will be still minor

Thanks for pointing out this issue!
