### ISSUE TITLE
Not existent @import paths

### ISSUE THREAD

**Issue by MaxAlekseyev** [SnowdogApps/magento2-frontools#446]
Hello,

The project is new for me. Just researched styles.scss imports section, some paths are absent but now any compilation errors.
How that can happened?

For example @import '../Magento_AdvancedCheckout/styles/module'; is absent in theme dir, no erro, but how did compiler fount this way?

**Comment by Igloczek** [comment]
Could you send some links to the files that confuses you? In this project we don't have any `styles.scss`, there are just tools to compile it.

**Comment by Igloczek** [comment]
If you are reffering to [SASS version of Blank theme](https://github.com/SnowdogApps/magento2-theme-blank-sass), and this line in [styles.scss](https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/master/styles/styles.scss#L38), the [file to import is in the repository](https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/master/Magento_AdvancedCheckout/styles/_module.scss)

**Comment by MaxAlekseyev** [comment]
Sure, I'm revising the project and wondering every day. Why there are this imports there? Why there no errors if the folders are absent?  Absoltely  strange to me situation. Thanks for you time!

Theme dirs structure and styles.less attached

[theme_structure_and_styles.zip](https://github.com/SnowdogApps/magento2-frontools/files/7520271/theme_structure_and_styles.zip)
y

**Comment by Igloczek** [comment]
Looks like you have a child theme, so tools handle the inheritance of files, that's how things in Magento are handled. The mechanism behind it is simple, it takes all files from the parent, unless file with exactly the same name exist in the child, so for compilation it's like a homogenous piece.

If you are curious about implementation details, please check out  https://github.com/SnowdogApps/magento2-frontools/blob/master/helpers/inheritance-resolver.mjs

Meanwhile, I'm going to close this issue, since there is nothing to fix there. For the future, please use "Discussions" section, for this type of stuff.
