### ISSUE TITLE
Improve CSS and SASS linting

### ISSUE THREAD

**Issue by Igloczek** [SnowdogApps/magento2-frontools#62]
Connect linting with watching files - we should be able to lint only recently changed files, to not have to dig though enormous output.

**Comment by timneutkens** [comment]
Hey @Igloczek, having holidays this week. Saw you implemented linting and code standards. Good job! I started implementing https://www.npmjs.com/package/gulp-watch as alternative to `gulp.watch` because one of my colleagues said it would beneficial if new files are detected automagically. gulp-watch also sends which file has changed (which `gulp.watch` does not do.

**Comment by Igloczek** [comment]
Cool, but you can get recently modified file in `gulp.watch` too, via `event` parameter 😉

**Comment by Igloczek** [comment]
Thing related to watching was moved to #116

**Comment by Igloczek** [comment]
Done - Will be released with 1.1.0
